---
version: v0
exports:
  - name: onUserSendMessageRequest
    description: >-
      This export is called whenever a user requests that a message be sent to the channel.
      Returning `false` blocks the message from further processing.
    x-codeSamples:
      - lang: typescript
        source: |
          function onUserSendMessageRequest(req: SendMessageRequest) {
            const { forwardMessage } = Host.getFunctions();
            req.message = req.message.toUpperCase()
            forwardMessage(req)
          }
    parameters:
      - description: The message request including the originating user
        $ref: '#/components/parameters/SendMessageRequestPtr'
    returns: []
  # - name: onUserHistoryRequest
  # - name: onUserSubscribeRequest
  # - name: onAutomationSubscribeRequest
  # - name: onAutomationMessageRequest
#imports: {}
  # - name: subscribeUser
  # - name: unsubscribeUser
  # - name: blockUser
  # - name: forwardMessage
  # - name: sendMessage
  # - name: subscribeAutomation
components:
  parameters:
    SendMessageRequestPtr:
      name: sendMessageRequestPtr
      description: an Extism pointer to a SendMessageRequest
      schema:
        type: integer
        format: ExtismPointer
        ref: '#/schemas/SendMessageRequest'
  schemas:
    User:
      name: User
      description: A representation of a user
      contentType: application/json
      properties:
        username:
          name: Username
          description: A username
          type: string
        id:
          name: User id
          description: A UUID representing the user
          type: string
          format: uuid
    SendMessageRequest:
      name: SendMessageRequest
      description: A user requests to send a message to the channel
      contentType: application/json
      required: ['user', 'message']
      properties:
        user:
          type: object
          $ref: '#/components/schemas/User'
        message:
          type: string
