# If you're running your own XTP (or using your own app on staging) this schema
# belongs to an extension point named "chat". 
#
# We should keep the XTP app that the deployed service uses in sync with this
# schema.
version: v1-draft
exports:
  handle:
    input:
      $ref: "#/components/schemas/IncomingEvent"
      contentType: application/json

imports:
  react:
    input:
      $ref: "#/components/schemas/OutgoingReaction"
      contentType: application/json
    output:
      $ref: "#/components/schemas/HandlerResult"
      contentType: application/json

  request:
    input:
      $ref: "#/components/schemas/OutgoingRequest"
      contentType: application/json
    output:
      $ref: "#/components/schemas/HandlerResult"
      contentType: application/json

  sendMessage:
    input:
      $ref: "#/components/schemas/OutgoingMessage"
      contentType: application/json
    output:
      $ref: "#/components/schemas/HandlerResult"
      contentType: application/json

  watchMessage:
    input:
      type: string
      description: the id of a message to watch
      contentType: text/plain; charset=utf-8
    output:
      $ref: "#/components/schemas/HandlerResult"
      contentType: application/json

components:
  schemas:
    IncomingEvent:
      description: An incoming event
      properties:
        kind:
          $ref: '#/components/schemas/EventKind'

        message:
          $ref: '#/components/schemas/IncomingMessage'
          nullable: true
        reaction:
          $ref: '#/components/schemas/IncomingReaction'
          nullable: true
        response: 
          $ref: '#/components/schemas/IncomingResponse'
          nullable: true

        channel:
          type: string
          description: The channel the message was received in

    EventKind:
      description: "The kind of event"
      enum: ["content", "watch:reference", "watch:reaction:added", "watch:reaction:removed", "http:response"]

    OutgoingRequest:
      description: An HTTP request
      properties:
        method:
          description: the http method
          type: string
        url:
          description: the url
          type: string
        headers:
          description: the http headers
          type: object
        body:
          description: the http body
          type: string

    OutgoingReaction:
      description: send a reaction
      properties:
        messageId:
          type: string
          description: the message id
        with:
          type: string
          description: The emoji reaction

    IncomingResponse:
      description: We received a response
      properties:
        id:
          type: string
          description: the identifier the plugin sent
        status:
          description: the http status code
          type: number
        headers:
          description: the http headers
          type: object
        body:
          description: the http body
          type: string

    IncomingReaction:
      description: A reaction happened
      properties:
        message:
          $ref: '#/components/schemas/IncomingMessage'
        from:
          type: string
          description: The username that reacted
        with:
          type: string
          description: The emoji reaction

    IncomingMessage:
      description: An incoming message
      properties:
        id:
          type: string
          description: An id identifying the message.
        content:
          type: string
          description: The message text
        author:
          type: object
          description: The author of the message
        reference:
          type: string
          description: The id of the message to which this message replies
          nullable: true

    OutgoingMessage:
      description: An outgoing message
      properties:
        message:
          type: string
          description: The message text
        channel:
          type: string
          description: The channel the message was received in
          nullable: true
        reply:
          type: string
          description: A message ID to reply to
          nullable: true

    HandlerResult:
      description: A result.
      properties:
        id:
          type: string
          description: An id for the result
        errorCode:
          type: number
          description: |
            An error code. Zero indicates success. Negative numbers indicate failure.
