# If you're running your own XTP (or using your own app on staging) this schema
# belongs to an extension point named "chat". 
#
# We should keep the XTP app that the deployed service uses in sync with this
# schema.
exports:
  - name: handle_message
    input:
      type: string
      contentType: text/plain; charset=UTF-8
      description: The message sent to Discord
    output:
      type: string
      contentType: text/plain; charset=UTF-8
      description: The Bot's reply
version: v1-draft
