app_id = "app_01hvhzafnwfb5bewmybe888ff8"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01j24z4yc2emetf0hysrnyg41j"
name = "keanu"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "npm run build"
