name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build docker service images 
        id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          load: true
          tags: latest
          cache-from: type=gha,scope=discordbot
          cache-to: type=gha,mode=max,scope=discordbot

