app_id = "app_01j8r463d3f6c91hdevkctb7cw"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01j8r4jqawfd6tjxh85t3988kc"
name = "haiku"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "sh prepare.sh && npm run build"

  # xtp plugin init runs this script to format the plugin code
  format = "npm run format"

  # xtp plugin init runs this script before running the format script
  prepare = "sh prepare.sh && npm install"
